// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZLYWauOaqq2aj0tyux6eKz0kPrz8-fJs',
    appId: '1:663678109296:web:66075428d0bb8c93e1d6b5',
    messagingSenderId: '663678109296',
    projectId: 'lets-spill',
    authDomain: 'lets-spill.firebaseapp.com',
    storageBucket: 'lets-spill.firebasestorage.app',
    measurementId: 'G-YYF7MED5DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3MARNK5BI0DLjQJJCYyJ9GWv6Y6n20n8',
    appId: '1:663678109296:android:59d66ab207d4ea82e1d6b5',
    messagingSenderId: '663678109296',
    projectId: 'lets-spill',
    storageBucket: 'lets-spill.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFnAUltByZTJwDYOUDknIWX_8Vgg5hkCs',
    appId: '1:663678109296:ios:111900e0563c322ce1d6b5',
    messagingSenderId: '663678109296',
    projectId: 'lets-spill',
    storageBucket: 'lets-spill.firebasestorage.app',
    iosBundleId: 'com.letsspill.letSSpill',
  );
}
